##---
# Source: olm/templates/0000_30_06-rh-operators.configmap.yaml

kind: ConfigMap
apiVersion: v1
metadata:
  name: maistra-operators
  namespace: openshift-operator-lifecycle-manager

data:
  customResourceDefinitions: |-
    - apiVersion: apiextensions.k8s.io/v1beta1
      kind: CustomResourceDefinition
      metadata:
        name: installations.istio.openshift.com
      spec:
        group: istio.openshift.com
        names:
          kind: Installation
          plural: installations
          singular: installation
        scope: Namespaced
        version: v1
      
  clusterServiceVersions: |-
    - #! validate-crd: ./deploy/chart/templates/03-clusterserviceversion.crd.yaml
      #! parse-kind: ClusterServiceVersion
      apiVersion: operators.coreos.com/v1alpha1
      kind: ClusterServiceVersion
      metadata:
        name: maistra.v0.5.0
        namespace: placeholder
      spec:
        displayName: Maistra
        description: Maistra, otherwise known as OpenShift Service Mesh, is Red Hat's version of Istio.
        keywords: ['service mesh', 'istio']
        maintainers:
        - name: Red Hat
          email: istio-feedback@redhat.com
        provider:
          name: Red Hat
        links:
        - name: Documentation
          url: https://maistra.io
        install:
          strategy: deployment
          spec:
            permissions:
            - serviceAccountName: istio-operator
              rules:
              - apiGroups:
                - istio.openshift.com
                resources:
                - "*"
                verbs:
                - "*"
              - apiGroups:
                - ""
                resources:
                - pods
                - services
                - endpoints
                - persistentvolumeclaims
                - events
                - configmaps
                - secrets
                - securitycontextconstraints
                verbs:
                - "*"
              - apiGroups:
                - apps
                resources:
                - deployments
                - daemonsets
                - replicasets
                - statefulsets
                verbs:
                - "*"
            clusterPermissions:
            deployments:
            - name: istio-operator
              namespace: istio-operator
              spec:
                replicas: 1
                strategy:
                  type: RollingUpdate
                selector:
                  matchLabels:
                    name: istio-operator
                template:
                  metadata:
                    labels:
                      name: istio-operator
                  spec:
                     containers:
                        - name: istio-operator
                          image: maistra/istio-operator-centos7:0.5.0
                          ports:
                          - containerPort: 60000
                            name: metrics
                          command:
                          - istio-operator
                          imagePullPolicy: Always
                          env:
                            - name: WATCH_NAMESPACE
                              valueFrom:
                                fieldRef:
                                  fieldPath: metadata.namespace
                            - name: OPERATOR_NAME
                              value: "istio-operator"
        maturity: alpha
        version: 0.5.0
        apiservicedefinitions:
        customresourcedefinitions:
          owned:
          - name: installations.istio.openshift.com
          version: v1
          kind: Installation
          displayName: Maistra Installation
          description: CRD representing Maistra installation options
          
  packages: |-
    - #! package-manifest: ./deploy/chart/catalog_resources/rh-operators/svcat.v0.1.34.clusterserviceversion.yaml
      packageName: maistra
      channels:
      - name: alpha
        currentCSV: maistra.v0.5.0
      

